### ISSUE TITLE
画像のアップロード不備？

### ISSUE THREAD

**Issue by Kohki-Takatama** [yu-ka3028/home-dayori#14]
![スクリーンショット 2024-06-29 12 39 25](https://github.com/yu-ka3028/home-dayori/assets/132065581/b4d2719f-0800-439b-bec3-4a59d79f1b71)  

READMEにて、画像のアップロード不備と思わしき箇所があります。

**Comment by yu-ka3028** [comment]
たまさんありがとうございます！
修正いたしました！
